"""create in team members

Revision ID: 192cbc60a8c8
Revises: df966c51e5aa
Create Date: 2025-01-17 17:37:21.721105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192cbc60a8c8'
down_revision: Union[str, None] = 'df966c51e5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users" , schema=None) as batch_op:
        # batch_op.drop_constraint('fk_users_team_id', 'users', type_='foreignkey')
        batch_op.drop_column('team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_users_team_id', 'users', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
