"""create_team_table

Revision ID: 36f514f35dbd
Revises: b4f54323c7c3
Create Date: 2024-11-06 11:28:53.259506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f514f35dbd'
down_revision: Union[str, None] = 'b4f54323c7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('teams',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('create_time', sa.DateTime(), nullable=True),
        sa.Column('update_time', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('team_leader_id', sa.Integer(), nullable=True),
        sa.Column('members_limit', sa.Integer(), nullable=True),
        sa.Column('members_counter', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['team_leader_id'], ['users.id'], ondelete='CASCADE' , name='fk_team_leader'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
        op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
        op.create_foreign_key("fk_team_leader", 'projects', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    except Exception as e:
        print(e)
        print("Table already exists")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_team_leader", 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
