"""create_user_rolles

Revision ID: 38d4b317f959
Revises: c11714386054
Create Date: 2024-11-06 10:57:10.547918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d4b317f959'
down_revision: Union[str, None] = 'c11714386054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roll',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roll_id'), 'roll', ['id'], unique=False)
    op.create_index(op.f('ix_roll_name'), 'roll', ['name'], unique=False)
    op.create_table('users_roll',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('roll_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_roll_id'), 'users_roll', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_roll_id'), table_name='users_roll')
    op.drop_table('users_roll')
    op.drop_index(op.f('ix_roll_name'), table_name='roll')
    op.drop_index(op.f('ix_roll_id'), table_name='roll')
    op.drop_table('roll')
    # ### end Alembic commands ###
