"""add counter status

Revision ID: 65946a71417d
Revises: 6ce455f76dc0
Create Date: 2025-03-14 15:30:59.115037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65946a71417d'
down_revision: Union[str, None] = '6ce455f76dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_counter', sa.Column('is_counting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_counter', 'is_counting')
    # ### end Alembic commands ###
