"""create_tasks_tables

Revision ID: 6b6f54cd8dc5
Revises: 36f514f35dbd
Create Date: 2024-11-06 12:34:59.105467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6f54cd8dc5'
down_revision: Union[str, None] = '36f514f35dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("fk_team_to_project", 'projects', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_team_to_project", 'projects', type_='foreignkey')
    # ### end Alembic commands ###
