"""roll_to_user

Revision ID: 70fe498bed30
Revises: 197b83c34ec2
Create Date: 2024-11-06 13:08:12.355506

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70fe498bed30"
down_revision: Union[str, None] = "197b83c34ec2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users_roll") as batch_op:
        batch_op.create_foreign_key(
            "fk_roll",
            "roll",
            ["roll_id"],
            ["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users_roll") as batch_op:
        batch_op.drop_constraint("fk_roll", type_="foreignkey")
    # ### end Alembic commands ###
