"""create_user_model

Revision ID: 8941d6ded15a
Revises: 31b0b8f2bbda
Create Date: 2024-11-06 10:42:44.303271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8941d6ded15a'
down_revision: Union[str, None] = '31b0b8f2bbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
