"""create project status

Revision ID: bba15c98790f
Revises: 689b06341644
Create Date: 2024-11-07 17:19:05.398233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba15c98790f'
down_revision: Union[str, None] = '689b06341644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     'project_status',
    #     sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    #     sa.Column('title', sa.String(), nullable=False),
    #     sa.Column('description', sa.String(), nullable=False),
    #     sa.Column('is_active', sa.Boolean(), nullable=True),
    #     sa.Column('create_time', sa.DateTime(), nullable=True),
    #     sa.Column('update_time', sa.DateTime(), nullable=True),
    #     sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_project_status_id'), 'project_status', ['id'], unique=False)
    
    # Use batch mode for altering constraints
    with op.batch_alter_table('users_roll') as batch_op:
        # batch_op.drop_constraint("user_roll", type_='foreignkey')
        batch_op.create_foreign_key("fk_user_roll", 'roll', ['roll_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_roll') as batch_op:
        # batch_op.drop_constraint("user_roll", type_='foreignkey')
        batch_op.create_foreign_key("fk_user_roll", 'roll', ['roll_id'], ['id'])
    
    op.drop_index(op.f('ix_project_status_id'), table_name='project_status')
    op.drop_table('project_status')
    # ### end Alembic commands ###

